<?php
namespace controllers\crud\viewers;

use Ajax\semantic\html\elements\HtmlLabel;
use Ubiquity\controllers\crud\viewers\ModelViewer;
 /**
  * Class CrudGroupsViewer
  */
class CrudGroupsViewer extends ModelViewer{
    public function getCaptions($captions, $className){
        return ['Nom','Email','Utilisateurs'];
    }

    public function getModelDataTable($instances, $model, $totalCount, $page = 1){
        $dt = parent::getModelDataTable($instances, $model, $totalCount, $page);
        $dt->fieldAsLabel('name');
        $dt->setValueFunction('groups',function($v, $instance){
            return HtmlLabel::tag('',count($v));
        });
        return $dt;
    }

    public function recordsPerPage($model, $totalCount = 0){
        return parent::recordsPerPage($model, $totalCount); // TODO: Change the autogenerated stub
    }

    protected function getDataTableRowButtons(){
        return parent::getDataTableRowButtons(); // TODO: Change the autogenerated stub
    }

    public function getModelDataElement($instance, $model, $modal){
        return parent::getModelDataElement($instance, $model, $modal); // TODO: Change the autogenerated stub
    }

    public function getElementCaptions($captions, $className, $instance){
        return parent::getElementCaptions($captions, $className, $instance); // TODO: Change the autogenerated stub
    }

    public function isModal($objects, $model){
    }

    public function getForm($identifier, $instance, $updateUrl = 'updateModel'){
    }

    public function getFormCaptions($captions, $className, $instance){
    }


}
