<?php
namespace controllers\crud\datas;

use Ubiquity\controllers\crud\CRUDDatas;
 /**
  * Class CrudGroupsDatas
  */
class CrudGroupsDatas extends CRUDDatas{
    public function getFieldNames($model){
        return ['name','email','users'];
    }

    public function getFormFieldNames($model, $instance){
        return parent::getFormFieldNames($model, $instance); // TODO: Change the autogenerated stub
    }

    public function _getInstancesFilter($model){
        return parent::_getInstancesFilter($model); // TODO: Change the autogenerated stub
    }

    public function getManyToManyDatas($fkClass, $instance, $member){
        return parent::getManyToManyDatas($fkClass, $instance, $member); // TODO: Change the autogenerated stub
    }


}
