<?php
namespace controllers;
use Ubiquity\attributes\items\router\Get;
use Ubiquity\attributes\items\router\Post;
use Ubiquity\attributes\items\router\Route;
use Ubiquity\utils\http\USession;


/**
 * Controller TodoController
 **/
class TodoController extends ControllerBase{
  const CACHE_KEY = 'datas/lists/';
  const EMPTY_LIST_ID='not saved';
  const LIST_SESSION_KEY='list';
  const ACTIVE_LIST_SESSION_KEY='active-list';

  #[Route(path:"_default", name:'home' )]
  public function index(){
    if(USession::exists(self::LIST_SESSION_KEY)) {
      $list = USession::get(self::LIST_SESSION_KEY, []);
      return $this->displayList($list);
    }
    $this->displayList(['Test','Eau','Lait','Fruits','Bonbons']);
    $this->showMessage('Bienvenue !','TodoLists permet de gerer des listes...','info','info circle outline');

  }


  public function initialize()
  {
    parent::initialize(); // TODO: Change the autogenerated stub
    $this->menu();
  }


  #[Post(path: "todo/loadList/",name: "todo.loadListPost")]
	public function loadListFromForm(){

	}

#[Get(path: "todo/loadList/{uniqid}",name: "todo.loadList")]
	public function loadList(int $uniqid){

}

  #[Get(path: "todo/saveList",name: "todo.save")]
  public function saveList(){

  }
	#[Post(path: "todo/new/{force}",name: "todo.new")]
  public function newlist($force = false){
    if($force != false | !USession::exists(self::LIST_SESSION_KEY)){
      USession::set(self::LIST_SESSION_KEY, []);
      $this->displayList(USession::get(self::LIST_SESSION_KEY));
    }else if(USession::exists(self::LIST_SESSION_KEY)) {
      $this->showMessage("Nouvelle Liste", "Une liste existe déjà. Voulez vous la vider ?", "", "",
        [['url' =>Router::path('todos.new/1'),'caption'=>'Créer une nouvelle liste','style'=>'basic inverted'],
          ['url' =>Router::path('todos.menu'),'caption'=>'Annuler','style'=>'basic inverted']]);
      $this->displayList(USession::get(self::LIST_SESSION_KEY));
    }
  }


	#[Post(path: "todo/addElement",name: "todo.add")]
	public function addElement(){

	}


	#[Get(path: "todo/deleteElement/{index}",name: "todo.delete")]
	public function deleteElement($index){

	}


	#[Post(path: "todo/editElement/{index}",name: "todo.edit")]
	public function editElement($index){

	}



	public function menu(){

		$this->loadView('TodoController/menu.html');

	}

  private function displayList($list){
    $this->loadView('TodoController/display.html', ['list'=>$list]);
  }

  private function showMessage(string $header, string $message, string $type = '', string $icon = 'info circle',array $buttons=[]) {
    $this->loadView('TodoController/message.html', compact('header', 'type', 'icon', 'message','buttons'));
  }
}
//
